---
- name: configure tomcat9 
  hosts: all
  tasks:
    - name: install tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: edit the sam file
      copy:
         content: "miss you abitha take care"
         dest: sam
    - name: restarted tomcat9
      serice:
          name: tomcat9
          state: restarted
    - name: check tomcat9 connection server1
      uri:
        url:http://172.31.31.240
        status_code: 200
    - name: check tomact9 connection server2
      uri:
        url: http://172.31.25.202
        status_code: 200      
      
...
